### ISSUE TITLE
BlurImageView with image from Uri

### ISSUE THREAD

**Issue by franto** [chrfalch/NControl.Controls#19] opened 2016-02-21 06:13 UTC
When I'm using image from Uri, image is not blurred (I have tried on iOS). Can I use image from Uri with BlurImageView. Is there any special way how to load image fr BlurImageView. I'm still Xamarin newbie :)

**Comment by chrfalch** [comment] 2016-02-21 14:13
Can't reproduce this, tried changing an image that is read from an Uri to use `BlurImageView` and everything worked perfectly. 

If you can create a very quick reproduction and zip it up and attach it I can see if I can find the reason for the problem. Try creating a page that contains a regular Image and a BlurImageView both reading from the same Uri.

**Comment by franto** [comment] 2016-02-21 21:48
I thought it was maybe caused by size of Image, but I've tried few of them and nothing worked. Here i code for creating BlurImageView

`String profileUri = "http://www.bestservice.de/img_share/image/Products/Shevannai/Lara06_150.jpg";

```
        var blurredBkg = new BlurImageView {
            Aspect = Aspect.AspectFill,
            Source = ImageSource.FromUri(new Uri(profileUri))
        };
        myLayout.Children.Add(blurredBkg, () => new Rectangle(0, 0, myLayout.Width, myLayout.Height));`
```

myLayout is RelativeLayout

**Comment by chrfalch** [comment] 2016-02-21 22:04
Ok confirmed :-)

Chris

**Comment by franto** [comment] 2016-02-21 22:09
Ok, but you have working example, right? What's the difference? Or you're  not using ImageSource.FromUri?

**Comment by chrfalch** [comment] 2016-02-22 09:41
I have a working reproduction, will try to take a look at this during the
week. You can follow the progress on Github.

Thanks!

Chris

**Comment by chrfalch** [comment] 2016-02-24 17:19
Did you remember to call `NControls.Init ();` after the line `global::Xamarin.Forms.Forms.Init ();` in your app startup code?

**Comment by franto** [comment] 2016-02-24 22:19
I'm calling `NControlViewRenderer.Init ();` not `NControls.Init();` Is it wrong?

**Comment by chrfalch** [comment] 2016-02-25 07:48
NControlViewRenderer.Init() initializes the NControl library while
NControls.Init() initializes the NControl.Controls library - Try for
yourself and see :-) Closing this issue now.

**Closed as completed** 2016-02-25 07:49 UTC
Labels: bug, iOS

**Comment by tarunagrawal1990** [comment] 2019-05-06 15:22
Hi,

I am trying to use NControl.Controls.NetCore in Xamarin.Forms project, but it is not working in UWP.

There is no compile time error but the controls are not rendering.

I have seen that I need to call initialization method for NControls i.e. NControls.Init(), but it seems that it is not available in UWP.

I have also tried with NControlViewRenderer.Init() or by installing nuget of NControl.NetCore but not able to render the custom controls.

Any help would be appreciated.
Thanks.
